### ISSUE TITLE
Potential bug for refreshing the active stream session

### ISSUE THREAD

**Issue by carlosmmatos** [CrowdStrike/falcon-integration-gateway#123]
error output:
```sh
2022-06-27 13:54:21 fig cs_refresh INFO     Thread requested to stop
Exception in thread cs_refresh:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
2022-06-27 13:54:21 fig cs_refresh INFO     Thread requested to stop
Exception in thread cs_refresh:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
2022-06-27 13:54:21 fig cs_refresh INFO     Thread requested to stop
Exception in thread cs_refresh:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/fig/fig/falcon/stream.py", line 68, in run
    self.run()
  File "/fig/fig/falcon/stream.py", line 68, in run
    self.run()
  File "/fig/fig/falcon/stream.py", line 68, in run
    self.refresh_stream_session()
  File "/fig/fig/falcon/stream.py", line 78, in refresh_stream_session
    self.refresh_stream_session()
Exception in thread cs_refresh:
    self.refresh_stream_session()
  File "/fig/fig/falcon/stream.py", line 78, in refresh_stream_session
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.falcon_api.refresh_streaming_session(self.application_id, self.stream)
  File "/fig/fig/falcon/api.py", line 44, in refresh_streaming_session
  File "/fig/fig/falcon/stream.py", line 78, in refresh_stream_session
    self.falcon_api.refresh_streaming_session(self.application_id, self.stream)
  File "/fig/fig/falcon/api.py", line 44, in refresh_streaming_session
    self.run()
  File "/fig/fig/falcon/stream.py", line 68, in run
    self.refresh_stream_session()
  File "/fig/fig/falcon/stream.py", line 78, in refresh_stream_session
    self._command(action='refreshActiveStreamSession',
  File "/fig/fig/falcon/api.py", line 93, in _command
    self.falcon_api.refresh_streaming_session(self.application_id, self.stream)
    self._command(action='refreshActiveStreamSession',
  File "/fig/fig/falcon/api.py", line 44, in refresh_streaming_session
  File "/fig/fig/falcon/api.py", line 93, in _command
    raise ApiError('Error received from CrowdStrike Falcon platform: {}'.format(body['errors']))
fig.falcon.api.ApiError: Error received from CrowdStrike Falcon platform: [{'code': 404, 'message': 'no active stream session found'}]
    self.falcon_api.refresh_streaming_session(self.application_id, self.stream)
  File "/fig/fig/falcon/api.py", line 44, in refresh_streaming_session
    self._command(action='refreshActiveStreamSession',
  File "/fig/fig/falcon/api.py", line 93, in _command
    raise ApiError('Error received from CrowdStrike Falcon platform: {}'.format(body['errors']))
fig.falcon.api.ApiError: Error received from CrowdStrike Falcon platform: [{'code': 404, 'message': 'no active stream session found'}]
    raise ApiError('Error received from CrowdStrike Falcon platform: {}'.format(body['errors']))
fig.falcon.api.ApiError: Error received from CrowdStrike Falcon platform: [{'code': 404, 'message': 'no active stream session found'}]
    self._command(action='refreshActiveStreamSession',
  File "/fig/fig/falcon/api.py", line 93, in _command
    raise ApiError('Error received from CrowdStrike Falcon platform: {}'.format(body['errors']))
fig.falcon.api.ApiError: Error received from CrowdStrike Falcon platform: [{'code': 404, 'message': 'no active stream session found'}]
2022-06-27 13:54:24 fig cs_stream  INFO     Opening Streaming Connection
2022-06-27 13:54:24 fig cs_stream  INFO     Opening Streaming Connection
2022-06-27 13:54:24 fig cs_stream  INFO     Opening Streaming Connection
2022-06-27 13:54:24 fig cs_stream  INFO     Opening Streaming Connection
```

**Comment by carlosmmatos** [comment]
not an issue - this is being caused by mac/networking issues on host running container
